/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.13u-20020617-2210
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__)
#       if defined(_MSC_VER)
#               if defined(STATIC_LINKED)
#                       define SWIGEXPORT(a) a
#                       define SWIGIMPORT(a) extern a
#               else
#                       define SWIGEXPORT(a) __declspec(dllexport) a
#                       define SWIGIMPORT(a) extern a
#               endif
#       else
#               if defined(__BORLANDC__)
#                       define SWIGEXPORT(a) a _export
#                       define SWIGIMPORT(a) a _export
#               else
#                       define SWIGEXPORT(a) a
#                       define SWIGIMPORT(a) a
#               endif
#       endif
#else
#       define SWIGEXPORT(a) a
#       define SWIGIMPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#define SWIGRUNTIME(a) SWIGEXPORT(a)
#else
#define SWIGRUNTIME(a) static a
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

typedef struct swig_type_info {
  const char             *name;                 
  swig_converter_func     converter;
  const char             *str;
  swig_dycast_func        dcast;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
  void                   *clientdata;	
} swig_type_info;

#ifdef SWIG_NOINCLUDE

SWIGIMPORT(swig_type_info *) SWIG_TypeRegister(swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeCheck(char *c, swig_type_info *);
SWIGIMPORT(void *)           SWIG_TypeCast(swig_type_info *, void *);
SWIGIMPORT(swig_type_info *) SWIG_TypeDynamicCast(swig_type_info *, void **);
SWIGIMPORT(swig_type_info *) SWIG_TypeQuery(const char *);
SWIGIMPORT(void)             SWIG_TypeClientData(swig_type_info *, void *);

#else

static swig_type_info *swig_type_list = 0;

/* Register a type mapping with the type-checking */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeRegister(swig_type_info *ti)
{
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_type_list;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_type_list;
  swig_type_list = ti;

  /* Build linked lists */
 l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeCheck(char *c, swig_type_info *ty)
{
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  while (s) {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
	s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      return s;
    }
    s = s->next;
  }
  return 0;
}

/* Cast a pointer up an inheritance hierarchy */
SWIGRUNTIME(void *) 
SWIG_TypeCast(swig_type_info *ty, void *ptr) 
{
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Dynamic pointer casting. Down an inheritance hierarchy */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) 
{
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
     ty = (*ty->dcast)(ptr);
     if (ty) lastty = ty;
  }
  return lastty;
}

/* Search for a swig_type_info structure */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = swig_type_list;
  while (ty) {
    if (ty->str && (strcmp(name,ty->str) == 0)) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

/* Set the clientdata field for a type */
SWIGRUNTIME(void)
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_type_info *tc, *equiv;
  if (ti->clientdata) return;
  ti->clientdata = clientdata;
  equiv = ti->next;
  while (equiv) {
    if (!equiv->converter) {
      tc = swig_type_list;
      while (tc) {
	if ((strcmp(tc->name, equiv->name) == 0))
	  SWIG_TypeClientData(tc,clientdata);
	tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}
#endif

#ifdef __cplusplus
}

#endif

/* -----------------------------------------------------------------------------
 * perl5.swg
 *
 * Perl5 runtime library
 * $Header: /cvsroot/g2/g2/g2/perl/g2_wrap.c,v 1.2 2002/08/11 03:09:40 wagner Exp $
 * ----------------------------------------------------------------------------- */

#define SWIGPERL
#define SWIGPERL5
#ifdef __cplusplus
/* Needed on some windows machines---since MS plays funny
   games with the header files under C++ */
#include <math.h>
#include <stdlib.h>
extern "C" {
#endif
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

/* Get rid of free and malloc defined by perl */
#undef free
#undef malloc

#ifndef pTHX_
#define pTHX_
#endif

#include <string.h>
#ifdef __cplusplus
}
#endif

/* Note: SwigMagicFuncHack is a typedef used to get the C++
   compiler to just shut up already */

#ifdef PERL_OBJECT
#define MAGIC_PPERL  CPerlObj *pPerl = (CPerlObj *) this;
typedef int (CPerlObj::*SwigMagicFunc)(SV *, MAGIC *);

#ifdef __cplusplus
extern "C" {
#endif
typedef int (CPerlObj::*SwigMagicFuncHack)(SV *, MAGIC *);
#ifdef __cplusplus
}
#endif

#define SWIG_MAGIC(a,b) (SV *a, MAGIC *b)
#define SWIGCLASS_STATIC
#else
#define MAGIC_PPERL
#define SWIGCLASS_STATIC static
#ifndef MULTIPLICITY
#define SWIG_MAGIC(a,b) (SV *a, MAGIC *b)
typedef int (*SwigMagicFunc)(SV *, MAGIC *);

#ifdef __cplusplus
extern "C" {
#endif
typedef int (*SwigMagicFuncHack)(SV *, MAGIC *);
#ifdef __cplusplus
}
#endif


#else
#define SWIG_MAGIC(a,b) (struct interpreter *interp, SV *a, MAGIC *b)
typedef int (*SwigMagicFunc)(struct interpreter *, SV *, MAGIC *);
#ifdef __cplusplus
extern "C" {
#endif
typedef int (*SwigMagicFuncHack)(struct interpreter *, SV *, MAGIC *);
#ifdef __cplusplus
}
#endif

#endif
#endif

#if defined(WIN32) && defined(PERL_OBJECT) && !defined(PerlIO_exportFILE)
#define PerlIO_exportFILE(fh,fl) (FILE*)(fh)
#endif

/* Modifications for newer Perl 5.005 releases */

#if !defined(PERL_REVISION) || ((PERL_REVISION >= 5) && ((PERL_VERSION < 5) || ((PERL_VERSION == 5) && (PERL_SUBVERSION < 50))))
#ifndef PL_sv_yes
#define PL_sv_yes sv_yes
#endif
#ifndef PL_sv_undef
#define PL_sv_undef sv_undef
#endif
#ifndef PL_na
#define PL_na na
#endif
#endif

#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef SWIG_NOINCLUDE

#ifndef PERL_OBJECT
extern int SWIG_ConvertPtr(SV *, void **, swig_type_info *, int flags);
extern void SWIG_MakePtr(SV *, void *, swig_type_info *, int flags);
#else
extern int _SWIG_ConvertPtr(CPerlObj *, SV *, void **, swig_type_info *,int flags);
extern void _SWIG_MakePtr(CPerlObj *, SV *, void *, swig_type_info *, int flags);
#define SWIG_ConvertPtr(a,b,c,d) _SWIG_ConvertPtr(pPerl,a,b,c,d)
#define SWIG_MakePtr(a,b,c,d) _SWIG_MakePtr(pPerl,a,b,c,d)
#endif

#else

/* Function for getting a pointer value */

#ifndef PERL_OBJECT
SWIGRUNTIME(int) 
SWIG_ConvertPtr(SV *sv, void **ptr, swig_type_info *_t, int flags)
#else
#define SWIG_ConvertPtr(a,b,c,d) _SWIG_ConvertPtr(pPerl,a,b,c,d)
SWIGRUNTIME(int)
_SWIG_ConvertPtr(CPerlObj *pPerl, SV *sv, void **ptr, swig_type_info *_t, int flags)
#endif
{
  char *_c;
  swig_type_info *tc;
  IV   tmp;

  /* If magical, apply more magic */
  if (SvGMAGICAL(sv))
    mg_get(sv);

  /* Check to see if this is an object */
  if (sv_isobject(sv)) {
    SV *tsv = (SV*) SvRV(sv);
    if ((SvTYPE(tsv) == SVt_PVHV)) {
      MAGIC *mg;
      if (SvMAGICAL(tsv)) {
	mg = mg_find(tsv,'P');
	if (mg) {
	  SV *rsv = mg->mg_obj;
	  if (sv_isobject(rsv)) {
	    tmp = SvIV((SV*)SvRV(rsv));
	  }
	}
      } else {
	return -1;
      }
    } else {
      tmp = SvIV((SV*)SvRV(sv));
    }
    if (!_t) {
      *(ptr) = (void *) tmp;
      return 0;
    }
  } else if (! SvOK(sv)) {            /* Check for undef */
    *(ptr) = (void *) 0;
    return 0;
  } else if (SvTYPE(sv) == SVt_RV) {  /* Check for NULL pointer */
    *(ptr) = (void *) 0;
    if (!SvROK(sv)) 
      return 0;
    else
      return -1;
  } else {                            /* Don't know what it is */
      *(ptr) = (void *) 0;
      return -1;
  }
  if (_t) {
    /* Now see if the types match */      
    _c = HvNAME(SvSTASH(SvRV(sv)));
    tc = SWIG_TypeCheck(_c,_t);
    if (!tc) {
      *ptr = (void *) tmp;
      return -1;
    }
    *ptr = SWIG_TypeCast(tc,(void *)tmp);
    return 0;
  }
  *ptr = (void *) tmp;
  return 0;
}
#ifndef PERL_OBJECT
SWIGRUNTIME(void) 
SWIG_MakePtr(SV *sv, void *ptr, swig_type_info *t,int flags)
#else
#define SWIG_MakePtr(a,b,c,d) _SWIG_MakePtr(pPerl,a,b,c,d)
SWIGRUNTIME(void)
_SWIG_MakePtr(CPerlObj *pPerl, SV *sv, void *ptr, swig_type_info *t, int flags)
#endif
{
  sv_setref_pv(sv, (char *) t->name, ptr);
}

#endif

typedef XS(SwigPerlWrapper);
typedef SwigPerlWrapper *SwigPerlWrapperPtr;

/* Structure for command table */
typedef struct {
  const char         *name;
  SwigPerlWrapperPtr  wrapper;
} swig_command_info;

/* Information for constant table */

#define SWIG_INT     1
#define SWIG_FLOAT   2
#define SWIG_STRING  3
#define SWIG_POINTER 4
#define SWIG_BINARY  5

/* Constant information structure */
typedef struct swig_constant_info {
    int              type;
    const char      *name;
    long             lvalue;
    double           dvalue;
    void            *pvalue;
    swig_type_info **ptype;
} swig_constant_info;

#ifdef __cplusplus
}
#endif

/* Structure for variable table */
typedef struct {
  const char   *name;
  SwigMagicFunc   set;
  SwigMagicFunc   get;
  swig_type_info  **type;
} swig_variable_info;

/* Magic variable code */
#ifndef PERL_OBJECT
#define swig_create_magic(s,a,b,c) _swig_create_magic(s,a,b,c)
  #ifndef MULTIPLICITY 
       static void _swig_create_magic(SV *sv, char *name, int (*set)(SV *, MAGIC *), int \
(*get)(SV *,MAGIC *)) { 
  #else 
       static void _swig_create_magic(SV *sv, char *name, int (*set)(struct interpreter*,\
 SV *, MAGIC *), int (*get)(struct interpreter*, SV *,MAGIC *)) { 
  #endif 
#else
#define swig_create_magic(s,a,b,c) _swig_create_magic(pPerl,s,a,b,c)
static void _swig_create_magic(CPerlObj *pPerl, SV *sv, const char *name, int (CPerlObj::*set)(SV *, MAGIC *), int (CPerlObj::*get)(SV *, MAGIC *)) {
#endif
  MAGIC *mg;
  sv_magic(sv,sv,'U',(char *) name,strlen(name));
  mg = mg_find(sv,'U');
  mg->mg_virtual = (MGVTBL *) malloc(sizeof(MGVTBL));
  mg->mg_virtual->svt_get = (SwigMagicFuncHack) get;
  mg->mg_virtual->svt_set = (SwigMagicFuncHack) set;
  mg->mg_virtual->svt_len = 0;
  mg->mg_virtual->svt_clear = 0;
  mg->mg_virtual->svt_free = 0;
}







/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_double swig_types[0] 
#define  SWIGTYPE_p_int swig_types[1] 
static swig_type_info *swig_types[3];

/* -------- TYPES TABLE (END) -------- */

#define SWIG_init    boot_g2

#define SWIG_name   "g2::boot_g2"
#define SWIG_prefix "g2::"

#ifdef __cplusplus
extern "C"
#endif
#ifndef PERL_OBJECT
#ifndef MULTIPLICITY
SWIGEXPORT(void) SWIG_init (CV* cv);
#else
SWIGEXPORT(void) SWIG_init (pTHXo_ CV* cv);
#endif
#else
SWIGEXPORT(void) SWIG_init (CV *cv, CPerlObj *);
#endif


#include "g2.h"
#if defined(DO_X11)
#include "g2_X11.h"
#endif
#if defined(DO_PS)
#include "g2_PS.h"
#endif
#if defined(DO_GD)
#include "g2_gd.h"
#endif
#if defined(DO_WIN32)
#include "WIN32/g2_win32.h"
#endif

extern void g2_query_pointer(int,double *,double *,unsigned int *);
#ifdef PERL_OBJECT
#define MAGIC_CLASS _wrap_g2_var::
class _wrap_g2_var : public CPerlObj {
public:
#else
#define MAGIC_CLASS
#endif
SWIGCLASS_STATIC int swig_magic_readonly(pTHX_ SV *sv, MAGIC *mg) {
    MAGIC_PPERL
    sv = sv; mg = mg;
    croak("Value is read-only.");
    return 0;
}


#ifdef PERL_OBJECT
};
#endif

#ifdef __cplusplus
extern "C" {
#endif
XS(_wrap_g2_open_PS) {
    char *arg1 ;
    int arg2 ;
    int arg3 ;
    int result;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 3) || (items > 3)) {
        croak("Usage: g2_open_PS(file_name,paper,orientation);");
    }
    if (!SvOK((SV*) ST(0))) arg1 = 0;
    else arg1 = (char *) SvPV(ST(0), PL_na);
    arg2 = (int) SvIV(ST(1));
    arg3 = (int) SvIV(ST(2));
    result = (int)g2_open_PS((char const *)arg1,(enum g2_PS_paper)arg2,(enum g2_PS_orientation)arg3);
    
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++), (IV) result);
    XSRETURN(argvi);
}


XS(_wrap_g2_open_EPSF) {
    char *arg1 ;
    int result;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 1) || (items > 1)) {
        croak("Usage: g2_open_EPSF(file_name);");
    }
    if (!SvOK((SV*) ST(0))) arg1 = 0;
    else arg1 = (char *) SvPV(ST(0), PL_na);
    result = (int)g2_open_EPSF((char const *)arg1);
    
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++), (IV) result);
    XSRETURN(argvi);
}


XS(_wrap_g2_open_EPSF_CLIP) {
    char *arg1 ;
    long arg2 ;
    long arg3 ;
    int result;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 3) || (items > 3)) {
        croak("Usage: g2_open_EPSF_CLIP(file_name,width,height);");
    }
    if (!SvOK((SV*) ST(0))) arg1 = 0;
    else arg1 = (char *) SvPV(ST(0), PL_na);
    arg2 = (long) SvIV(ST(1));
    arg3 = (long) SvIV(ST(2));
    result = (int)g2_open_EPSF_CLIP((char const *)arg1,arg2,arg3);
    
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++), (IV) result);
    XSRETURN(argvi);
}


XS(_wrap_g2_open_gd) {
    char *arg1 ;
    int arg2 ;
    int arg3 ;
    int arg4 ;
    int result;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 4) || (items > 4)) {
        croak("Usage: g2_open_gd(filename,width,height,gd_type);");
    }
    if (!SvOK((SV*) ST(0))) arg1 = 0;
    else arg1 = (char *) SvPV(ST(0), PL_na);
    arg2 = (int) SvIV(ST(1));
    arg3 = (int) SvIV(ST(2));
    arg4 = (int) SvIV(ST(3));
    result = (int)g2_open_gd((char const *)arg1,arg2,arg3,(enum g2_gd_type)arg4);
    
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++), (IV) result);
    XSRETURN(argvi);
}


XS(_wrap_g2_open_win32) {
    int arg1 ;
    int arg2 ;
    char *arg3 ;
    int arg4 ;
    int result;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 4) || (items > 4)) {
        croak("Usage: g2_open_win32(width,height,filename,type);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (int) SvIV(ST(1));
    if (!SvOK((SV*) ST(2))) arg3 = 0;
    else arg3 = (char *) SvPV(ST(2), PL_na);
    arg4 = (int) SvIV(ST(3));
    result = (int)g2_open_win32(arg1,arg2,(char const *)arg3,arg4);
    
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++), (IV) result);
    XSRETURN(argvi);
}


XS(_wrap_g2_open_vd) {
    int result;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 0) || (items > 0)) {
        croak("Usage: g2_open_vd();");
    }
    result = (int)g2_open_vd();
    
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++), (IV) result);
    XSRETURN(argvi);
}


XS(_wrap_g2_attach) {
    int arg1 ;
    int arg2 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 2) || (items > 2)) {
        croak("Usage: g2_attach(vd_dev,dev);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (int) SvIV(ST(1));
    g2_attach(arg1,arg2);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_detach) {
    int arg1 ;
    int arg2 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 2) || (items > 2)) {
        croak("Usage: g2_detach(vd_dev,dev);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (int) SvIV(ST(1));
    g2_detach(arg1,arg2);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_close) {
    int arg1 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 1) || (items > 1)) {
        croak("Usage: g2_close(dev);");
    }
    arg1 = (int) SvIV(ST(0));
    g2_close(arg1);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_set_auto_flush) {
    int arg1 ;
    int arg2 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 2) || (items > 2)) {
        croak("Usage: g2_set_auto_flush(dev,on_off);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (int) SvIV(ST(1));
    g2_set_auto_flush(arg1,arg2);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_flush) {
    int arg1 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 1) || (items > 1)) {
        croak("Usage: g2_flush(dev);");
    }
    arg1 = (int) SvIV(ST(0));
    g2_flush(arg1);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_save) {
    int arg1 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 1) || (items > 1)) {
        croak("Usage: g2_save(dev);");
    }
    arg1 = (int) SvIV(ST(0));
    g2_save(arg1);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_set_coordinate_system) {
    int arg1 ;
    double arg2 ;
    double arg3 ;
    double arg4 ;
    double arg5 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 5) || (items > 5)) {
        croak("Usage: g2_set_coordinate_system(dev,x_origin,y_origin,x_mul,y_mul);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (double) SvNV(ST(1));
    
    arg3 = (double) SvNV(ST(2));
    
    arg4 = (double) SvNV(ST(3));
    
    arg5 = (double) SvNV(ST(4));
    
    g2_set_coordinate_system(arg1,arg2,arg3,arg4,arg5);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_ld) {
    int result;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 0) || (items > 0)) {
        croak("Usage: g2_ld();");
    }
    result = (int)g2_ld();
    
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++), (IV) result);
    XSRETURN(argvi);
}


XS(_wrap_g2_set_ld) {
    int arg1 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 1) || (items > 1)) {
        croak("Usage: g2_set_ld(dev);");
    }
    arg1 = (int) SvIV(ST(0));
    g2_set_ld(arg1);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_ink) {
    int arg1 ;
    double arg2 ;
    double arg3 ;
    double arg4 ;
    int result;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 4) || (items > 4)) {
        croak("Usage: g2_ink(pd_dev,red,green,blue);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (double) SvNV(ST(1));
    
    arg3 = (double) SvNV(ST(2));
    
    arg4 = (double) SvNV(ST(3));
    
    result = (int)g2_ink(arg1,arg2,arg3,arg4);
    
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++), (IV) result);
    XSRETURN(argvi);
}


XS(_wrap_g2_pen) {
    int arg1 ;
    int arg2 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 2) || (items > 2)) {
        croak("Usage: g2_pen(dev,color);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (int) SvIV(ST(1));
    g2_pen(arg1,arg2);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_set_dash) {
    int arg1 ;
    int arg2 ;
    double *arg3 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 3) || (items > 3)) {
        croak("Usage: g2_set_dash(dev,N,dashes);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (int) SvIV(ST(1));
    {
        if (SWIG_ConvertPtr(ST(2), (void **) &arg3, SWIGTYPE_p_double,0) < 0) {
            croak("Type error in argument 3 of g2_set_dash. Expected %s", SWIGTYPE_p_double->name);
        }
    }
    g2_set_dash(arg1,arg2,arg3);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_set_font_size) {
    int arg1 ;
    double arg2 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 2) || (items > 2)) {
        croak("Usage: g2_set_font_size(dev,size);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (double) SvNV(ST(1));
    
    g2_set_font_size(arg1,arg2);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_set_line_width) {
    int arg1 ;
    double arg2 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 2) || (items > 2)) {
        croak("Usage: g2_set_line_width(dev,w);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (double) SvNV(ST(1));
    
    g2_set_line_width(arg1,arg2);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_clear_palette) {
    int arg1 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 1) || (items > 1)) {
        croak("Usage: g2_clear_palette(dev);");
    }
    arg1 = (int) SvIV(ST(0));
    g2_clear_palette(arg1);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_reset_palette) {
    int arg1 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 1) || (items > 1)) {
        croak("Usage: g2_reset_palette(dev);");
    }
    arg1 = (int) SvIV(ST(0));
    g2_reset_palette(arg1);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_allocate_basic_colors) {
    int arg1 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 1) || (items > 1)) {
        croak("Usage: g2_allocate_basic_colors(dev);");
    }
    arg1 = (int) SvIV(ST(0));
    g2_allocate_basic_colors(arg1);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_clear) {
    int arg1 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 1) || (items > 1)) {
        croak("Usage: g2_clear(dev);");
    }
    arg1 = (int) SvIV(ST(0));
    g2_clear(arg1);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_set_background) {
    int arg1 ;
    int arg2 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 2) || (items > 2)) {
        croak("Usage: g2_set_background(dev,color);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (int) SvIV(ST(1));
    g2_set_background(arg1,arg2);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_move) {
    int arg1 ;
    double arg2 ;
    double arg3 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 3) || (items > 3)) {
        croak("Usage: g2_move(dev,x,y);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (double) SvNV(ST(1));
    
    arg3 = (double) SvNV(ST(2));
    
    g2_move(arg1,arg2,arg3);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_move_r) {
    int arg1 ;
    double arg2 ;
    double arg3 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 3) || (items > 3)) {
        croak("Usage: g2_move_r(dev,dx,dy);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (double) SvNV(ST(1));
    
    arg3 = (double) SvNV(ST(2));
    
    g2_move_r(arg1,arg2,arg3);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_plot) {
    int arg1 ;
    double arg2 ;
    double arg3 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 3) || (items > 3)) {
        croak("Usage: g2_plot(dev,x,y);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (double) SvNV(ST(1));
    
    arg3 = (double) SvNV(ST(2));
    
    g2_plot(arg1,arg2,arg3);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_plot_r) {
    int arg1 ;
    double arg2 ;
    double arg3 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 3) || (items > 3)) {
        croak("Usage: g2_plot_r(dev,dx,dy);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (double) SvNV(ST(1));
    
    arg3 = (double) SvNV(ST(2));
    
    g2_plot_r(arg1,arg2,arg3);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_line) {
    int arg1 ;
    double arg2 ;
    double arg3 ;
    double arg4 ;
    double arg5 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 5) || (items > 5)) {
        croak("Usage: g2_line(dev,x1,y1,x2,y2);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (double) SvNV(ST(1));
    
    arg3 = (double) SvNV(ST(2));
    
    arg4 = (double) SvNV(ST(3));
    
    arg5 = (double) SvNV(ST(4));
    
    g2_line(arg1,arg2,arg3,arg4,arg5);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_line_r) {
    int arg1 ;
    double arg2 ;
    double arg3 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 3) || (items > 3)) {
        croak("Usage: g2_line_r(dev,dx,dy);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (double) SvNV(ST(1));
    
    arg3 = (double) SvNV(ST(2));
    
    g2_line_r(arg1,arg2,arg3);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_line_to) {
    int arg1 ;
    double arg2 ;
    double arg3 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 3) || (items > 3)) {
        croak("Usage: g2_line_to(dev,x,y);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (double) SvNV(ST(1));
    
    arg3 = (double) SvNV(ST(2));
    
    g2_line_to(arg1,arg2,arg3);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_poly_line) {
    int arg1 ;
    int arg2 ;
    double *arg3 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 3) || (items > 3)) {
        croak("Usage: g2_poly_line(dev,N_pt,points);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (int) SvIV(ST(1));
    {
        if (SWIG_ConvertPtr(ST(2), (void **) &arg3, SWIGTYPE_p_double,0) < 0) {
            croak("Type error in argument 3 of g2_poly_line. Expected %s", SWIGTYPE_p_double->name);
        }
    }
    g2_poly_line(arg1,arg2,arg3);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_triangle) {
    int arg1 ;
    double arg2 ;
    double arg3 ;
    double arg4 ;
    double arg5 ;
    double arg6 ;
    double arg7 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 7) || (items > 7)) {
        croak("Usage: g2_triangle(dev,x1,y1,x2,y2,x3,y3);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (double) SvNV(ST(1));
    
    arg3 = (double) SvNV(ST(2));
    
    arg4 = (double) SvNV(ST(3));
    
    arg5 = (double) SvNV(ST(4));
    
    arg6 = (double) SvNV(ST(5));
    
    arg7 = (double) SvNV(ST(6));
    
    g2_triangle(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_filled_triangle) {
    int arg1 ;
    double arg2 ;
    double arg3 ;
    double arg4 ;
    double arg5 ;
    double arg6 ;
    double arg7 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 7) || (items > 7)) {
        croak("Usage: g2_filled_triangle(dev,x1,y1,x2,y2,x3,y3);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (double) SvNV(ST(1));
    
    arg3 = (double) SvNV(ST(2));
    
    arg4 = (double) SvNV(ST(3));
    
    arg5 = (double) SvNV(ST(4));
    
    arg6 = (double) SvNV(ST(5));
    
    arg7 = (double) SvNV(ST(6));
    
    g2_filled_triangle(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_rectangle) {
    int arg1 ;
    double arg2 ;
    double arg3 ;
    double arg4 ;
    double arg5 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 5) || (items > 5)) {
        croak("Usage: g2_rectangle(dev,x1,y1,x2,y2);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (double) SvNV(ST(1));
    
    arg3 = (double) SvNV(ST(2));
    
    arg4 = (double) SvNV(ST(3));
    
    arg5 = (double) SvNV(ST(4));
    
    g2_rectangle(arg1,arg2,arg3,arg4,arg5);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_filled_rectangle) {
    int arg1 ;
    double arg2 ;
    double arg3 ;
    double arg4 ;
    double arg5 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 5) || (items > 5)) {
        croak("Usage: g2_filled_rectangle(dev,x1,y1,x2,y2);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (double) SvNV(ST(1));
    
    arg3 = (double) SvNV(ST(2));
    
    arg4 = (double) SvNV(ST(3));
    
    arg5 = (double) SvNV(ST(4));
    
    g2_filled_rectangle(arg1,arg2,arg3,arg4,arg5);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_polygon) {
    int arg1 ;
    int arg2 ;
    double *arg3 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 3) || (items > 3)) {
        croak("Usage: g2_polygon(dev,N_pt,points);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (int) SvIV(ST(1));
    {
        if (SWIG_ConvertPtr(ST(2), (void **) &arg3, SWIGTYPE_p_double,0) < 0) {
            croak("Type error in argument 3 of g2_polygon. Expected %s", SWIGTYPE_p_double->name);
        }
    }
    g2_polygon(arg1,arg2,arg3);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_filled_polygon) {
    int arg1 ;
    int arg2 ;
    double *arg3 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 3) || (items > 3)) {
        croak("Usage: g2_filled_polygon(dev,N_pt,points);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (int) SvIV(ST(1));
    {
        if (SWIG_ConvertPtr(ST(2), (void **) &arg3, SWIGTYPE_p_double,0) < 0) {
            croak("Type error in argument 3 of g2_filled_polygon. Expected %s", SWIGTYPE_p_double->name);
        }
    }
    g2_filled_polygon(arg1,arg2,arg3);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_circle) {
    int arg1 ;
    double arg2 ;
    double arg3 ;
    double arg4 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 4) || (items > 4)) {
        croak("Usage: g2_circle(dev,x,y,r);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (double) SvNV(ST(1));
    
    arg3 = (double) SvNV(ST(2));
    
    arg4 = (double) SvNV(ST(3));
    
    g2_circle(arg1,arg2,arg3,arg4);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_filled_circle) {
    int arg1 ;
    double arg2 ;
    double arg3 ;
    double arg4 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 4) || (items > 4)) {
        croak("Usage: g2_filled_circle(dev,x,y,r);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (double) SvNV(ST(1));
    
    arg3 = (double) SvNV(ST(2));
    
    arg4 = (double) SvNV(ST(3));
    
    g2_filled_circle(arg1,arg2,arg3,arg4);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_ellipse) {
    int arg1 ;
    double arg2 ;
    double arg3 ;
    double arg4 ;
    double arg5 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 5) || (items > 5)) {
        croak("Usage: g2_ellipse(dev,x,y,r1,r2);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (double) SvNV(ST(1));
    
    arg3 = (double) SvNV(ST(2));
    
    arg4 = (double) SvNV(ST(3));
    
    arg5 = (double) SvNV(ST(4));
    
    g2_ellipse(arg1,arg2,arg3,arg4,arg5);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_filled_ellipse) {
    int arg1 ;
    double arg2 ;
    double arg3 ;
    double arg4 ;
    double arg5 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 5) || (items > 5)) {
        croak("Usage: g2_filled_ellipse(dev,x,y,r1,r2);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (double) SvNV(ST(1));
    
    arg3 = (double) SvNV(ST(2));
    
    arg4 = (double) SvNV(ST(3));
    
    arg5 = (double) SvNV(ST(4));
    
    g2_filled_ellipse(arg1,arg2,arg3,arg4,arg5);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_arc) {
    int arg1 ;
    double arg2 ;
    double arg3 ;
    double arg4 ;
    double arg5 ;
    double arg6 ;
    double arg7 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 7) || (items > 7)) {
        croak("Usage: g2_arc(dev,x,y,r1,r2,a1,a2);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (double) SvNV(ST(1));
    
    arg3 = (double) SvNV(ST(2));
    
    arg4 = (double) SvNV(ST(3));
    
    arg5 = (double) SvNV(ST(4));
    
    arg6 = (double) SvNV(ST(5));
    
    arg7 = (double) SvNV(ST(6));
    
    g2_arc(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_filled_arc) {
    int arg1 ;
    double arg2 ;
    double arg3 ;
    double arg4 ;
    double arg5 ;
    double arg6 ;
    double arg7 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 7) || (items > 7)) {
        croak("Usage: g2_filled_arc(dev,x,y,r1,r2,a1,a2);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (double) SvNV(ST(1));
    
    arg3 = (double) SvNV(ST(2));
    
    arg4 = (double) SvNV(ST(3));
    
    arg5 = (double) SvNV(ST(4));
    
    arg6 = (double) SvNV(ST(5));
    
    arg7 = (double) SvNV(ST(6));
    
    g2_filled_arc(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_string) {
    int arg1 ;
    double arg2 ;
    double arg3 ;
    char *arg4 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 4) || (items > 4)) {
        croak("Usage: g2_string(dev,x,y,text);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (double) SvNV(ST(1));
    
    arg3 = (double) SvNV(ST(2));
    
    if (!SvOK((SV*) ST(3))) arg4 = 0;
    else arg4 = (char *) SvPV(ST(3), PL_na);
    g2_string(arg1,arg2,arg3,arg4);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_image) {
    int arg1 ;
    double arg2 ;
    double arg3 ;
    int arg4 ;
    int arg5 ;
    int *arg6 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 6) || (items > 6)) {
        croak("Usage: g2_image(dev,x,y,x_size,y_size,pens);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (double) SvNV(ST(1));
    
    arg3 = (double) SvNV(ST(2));
    
    arg4 = (int) SvIV(ST(3));
    arg5 = (int) SvIV(ST(4));
    {
        if (SWIG_ConvertPtr(ST(5), (void **) &arg6, SWIGTYPE_p_int,0) < 0) {
            croak("Type error in argument 6 of g2_image. Expected %s", SWIGTYPE_p_int->name);
        }
    }
    g2_image(arg1,arg2,arg3,arg4,arg5,arg6);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_set_QP) {
    int arg1 ;
    double arg2 ;
    int arg3 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 3) || (items > 3)) {
        croak("Usage: g2_set_QP(dev,d,shape);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (double) SvNV(ST(1));
    
    arg3 = (int) SvIV(ST(2));
    g2_set_QP(arg1,arg2,(enum QPshape)arg3);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_plot_QP) {
    int arg1 ;
    double arg2 ;
    double arg3 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 3) || (items > 3)) {
        croak("Usage: g2_plot_QP(dev,x,y);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (double) SvNV(ST(1));
    
    arg3 = (double) SvNV(ST(2));
    
    g2_plot_QP(arg1,arg2,arg3);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_query_pointer) {
    int arg1 ;
    double *arg2 ;
    double *arg3 ;
    unsigned int *arg4 ;
    double temp2 ;
    double temp3 ;
    unsigned int temp4 ;
    int argvi = 0;
    dXSARGS;
    
    {
        arg2 = &temp2;
    }
    {
        arg3 = &temp3;
    }
    {
        arg4 = &temp4;
    }
    if ((items < 1) || (items > 1)) {
        croak("Usage: g2_query_pointer(dev);");
    }
    arg1 = (int) SvIV(ST(0));
    g2_query_pointer(arg1,arg2,arg3,arg4);
    
    
    {
        if (argvi >= items) {
            EXTEND(sp,1);
        }
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi),(double) *(arg2));
        argvi++;
    }
    {
        if (argvi >= items) {
            EXTEND(sp,1);
        }
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi),(double) *(arg3));
        argvi++;
    }
    {
        if (argvi >= items) {
            EXTEND(sp,1);
        }
        ST(argvi) = sv_newmortal();
        sv_setiv(ST(argvi),(IV) *(arg4));
        argvi++;
    }
    XSRETURN(argvi);
}


XS(_wrap_g2_spline) {
    int arg1 ;
    int arg2 ;
    double *arg3 ;
    int arg4 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 4) || (items > 4)) {
        croak("Usage: g2_spline(id,n,points,o);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (int) SvIV(ST(1));
    {
        if (SWIG_ConvertPtr(ST(2), (void **) &arg3, SWIGTYPE_p_double,0) < 0) {
            croak("Type error in argument 3 of g2_spline. Expected %s", SWIGTYPE_p_double->name);
        }
    }
    arg4 = (int) SvIV(ST(3));
    g2_spline(arg1,arg2,arg3,arg4);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_b_spline) {
    int arg1 ;
    int arg2 ;
    double *arg3 ;
    int arg4 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 4) || (items > 4)) {
        croak("Usage: g2_b_spline(id,n,points,o);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (int) SvIV(ST(1));
    {
        if (SWIG_ConvertPtr(ST(2), (void **) &arg3, SWIGTYPE_p_double,0) < 0) {
            croak("Type error in argument 3 of g2_b_spline. Expected %s", SWIGTYPE_p_double->name);
        }
    }
    arg4 = (int) SvIV(ST(3));
    g2_b_spline(arg1,arg2,arg3,arg4);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_raspln) {
    int arg1 ;
    int arg2 ;
    double *arg3 ;
    double arg4 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 4) || (items > 4)) {
        croak("Usage: g2_raspln(id,n,points,tn);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (int) SvIV(ST(1));
    {
        if (SWIG_ConvertPtr(ST(2), (void **) &arg3, SWIGTYPE_p_double,0) < 0) {
            croak("Type error in argument 3 of g2_raspln. Expected %s", SWIGTYPE_p_double->name);
        }
    }
    arg4 = (double) SvNV(ST(3));
    
    g2_raspln(arg1,arg2,arg3,arg4);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_para_3) {
    int arg1 ;
    int arg2 ;
    double *arg3 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 3) || (items > 3)) {
        croak("Usage: g2_para_3(id,n,points);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (int) SvIV(ST(1));
    {
        if (SWIG_ConvertPtr(ST(2), (void **) &arg3, SWIGTYPE_p_double,0) < 0) {
            croak("Type error in argument 3 of g2_para_3. Expected %s", SWIGTYPE_p_double->name);
        }
    }
    g2_para_3(arg1,arg2,arg3);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_para_5) {
    int arg1 ;
    int arg2 ;
    double *arg3 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 3) || (items > 3)) {
        croak("Usage: g2_para_5(id,n,points);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (int) SvIV(ST(1));
    {
        if (SWIG_ConvertPtr(ST(2), (void **) &arg3, SWIGTYPE_p_double,0) < 0) {
            croak("Type error in argument 3 of g2_para_5. Expected %s", SWIGTYPE_p_double->name);
        }
    }
    g2_para_5(arg1,arg2,arg3);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_filled_spline) {
    int arg1 ;
    int arg2 ;
    double *arg3 ;
    int arg4 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 4) || (items > 4)) {
        croak("Usage: g2_filled_spline(id,n,points,o);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (int) SvIV(ST(1));
    {
        if (SWIG_ConvertPtr(ST(2), (void **) &arg3, SWIGTYPE_p_double,0) < 0) {
            croak("Type error in argument 3 of g2_filled_spline. Expected %s", SWIGTYPE_p_double->name);
        }
    }
    arg4 = (int) SvIV(ST(3));
    g2_filled_spline(arg1,arg2,arg3,arg4);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_filled_b_spline) {
    int arg1 ;
    int arg2 ;
    double *arg3 ;
    int arg4 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 4) || (items > 4)) {
        croak("Usage: g2_filled_b_spline(id,n,points,o);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (int) SvIV(ST(1));
    {
        if (SWIG_ConvertPtr(ST(2), (void **) &arg3, SWIGTYPE_p_double,0) < 0) {
            croak("Type error in argument 3 of g2_filled_b_spline. Expected %s", SWIGTYPE_p_double->name);
        }
    }
    arg4 = (int) SvIV(ST(3));
    g2_filled_b_spline(arg1,arg2,arg3,arg4);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_filled_raspln) {
    int arg1 ;
    int arg2 ;
    double *arg3 ;
    double arg4 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 4) || (items > 4)) {
        croak("Usage: g2_filled_raspln(id,n,points,tn);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (int) SvIV(ST(1));
    {
        if (SWIG_ConvertPtr(ST(2), (void **) &arg3, SWIGTYPE_p_double,0) < 0) {
            croak("Type error in argument 3 of g2_filled_raspln. Expected %s", SWIGTYPE_p_double->name);
        }
    }
    arg4 = (double) SvNV(ST(3));
    
    g2_filled_raspln(arg1,arg2,arg3,arg4);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_filled_para_3) {
    int arg1 ;
    int arg2 ;
    double *arg3 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 3) || (items > 3)) {
        croak("Usage: g2_filled_para_3(id,n,points);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (int) SvIV(ST(1));
    {
        if (SWIG_ConvertPtr(ST(2), (void **) &arg3, SWIGTYPE_p_double,0) < 0) {
            croak("Type error in argument 3 of g2_filled_para_3. Expected %s", SWIGTYPE_p_double->name);
        }
    }
    g2_filled_para_3(arg1,arg2,arg3);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_filled_para_5) {
    int arg1 ;
    int arg2 ;
    double *arg3 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 3) || (items > 3)) {
        croak("Usage: g2_filled_para_5(id,n,points);");
    }
    arg1 = (int) SvIV(ST(0));
    arg2 = (int) SvIV(ST(1));
    {
        if (SWIG_ConvertPtr(ST(2), (void **) &arg3, SWIGTYPE_p_double,0) < 0) {
            croak("Type error in argument 3 of g2_filled_para_5. Expected %s", SWIGTYPE_p_double->name);
        }
    }
    g2_filled_para_5(arg1,arg2,arg3);
    
    
    XSRETURN(argvi);
}


XS(_wrap_g2_device_exist) {
    int arg1 ;
    int result;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 1) || (items > 1)) {
        croak("Usage: g2_device_exist(dix);");
    }
    arg1 = (int) SvIV(ST(0));
    result = (int)g2_device_exist(arg1);
    
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++), (IV) result);
    XSRETURN(argvi);
}



/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_double[] = {{"_p_double", 0, "double *"},{"_p_double"},{0}};
static swig_type_info _swigt__p_int[] = {{"_p_int", 0, "int *"},{"_p_int"},{0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_double, 
_swigt__p_int, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

static swig_constant_info swig_constants[] = {
{ SWIG_STRING,  (char *) SWIG_prefix "G2_VERSION", 0, 0, (void *)"0.41a", 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_A0", (long) g2_A0, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_A1", (long) g2_A1, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_A2", (long) g2_A2, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_A3", (long) g2_A3, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_A4", (long) g2_A4, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_A5", (long) g2_A5, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_A6", (long) g2_A6, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_A7", (long) g2_A7, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_A8", (long) g2_A8, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_A9", (long) g2_A9, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_B0", (long) g2_B0, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_B1", (long) g2_B1, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_B2", (long) g2_B2, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_B3", (long) g2_B3, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_B4", (long) g2_B4, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_B5", (long) g2_B5, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_B6", (long) g2_B6, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_B7", (long) g2_B7, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_B8", (long) g2_B8, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_B9", (long) g2_B9, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_B10", (long) g2_B10, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_Comm_10_Envelope", (long) g2_Comm_10_Envelope, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_C5_Envelope", (long) g2_C5_Envelope, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_DL_Envelope", (long) g2_DL_Envelope, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_Folio", (long) g2_Folio, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_Executive", (long) g2_Executive, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_Letter", (long) g2_Letter, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_Legal", (long) g2_Legal, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_Ledger", (long) g2_Ledger, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_Tabloid", (long) g2_Tabloid, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_PS_land", (long) g2_PS_land, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_PS_port", (long) g2_PS_port, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_PS_PostScript", (long) g2_PS_PostScript, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_PS_EPSF", (long) g2_PS_EPSF, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_PS_EPSF_CLIP", (long) g2_PS_EPSF_CLIP, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_gd_jpeg", (long) g2_gd_jpeg, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_gd_png", (long) g2_gd_png, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_win32", (long) g2_win32, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "g2_wmf32", (long) g2_wmf32, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "QPrect", (long) QPrect, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "QPcirc", (long) QPcirc, 0, 0, 0},
{0}
};
#ifdef __cplusplus
}
#endif
static swig_variable_info swig_variables[] = {
{0}
};
static swig_command_info swig_commands[] = {
{"g2::g2_open_PS", _wrap_g2_open_PS},
{"g2::g2_open_EPSF", _wrap_g2_open_EPSF},
{"g2::g2_open_EPSF_CLIP", _wrap_g2_open_EPSF_CLIP},
{"g2::g2_open_gd", _wrap_g2_open_gd},
{"g2::g2_open_win32", _wrap_g2_open_win32},
{"g2::g2_open_vd", _wrap_g2_open_vd},
{"g2::g2_attach", _wrap_g2_attach},
{"g2::g2_detach", _wrap_g2_detach},
{"g2::g2_close", _wrap_g2_close},
{"g2::g2_set_auto_flush", _wrap_g2_set_auto_flush},
{"g2::g2_flush", _wrap_g2_flush},
{"g2::g2_save", _wrap_g2_save},
{"g2::g2_set_coordinate_system", _wrap_g2_set_coordinate_system},
{"g2::g2_ld", _wrap_g2_ld},
{"g2::g2_set_ld", _wrap_g2_set_ld},
{"g2::g2_ink", _wrap_g2_ink},
{"g2::g2_pen", _wrap_g2_pen},
{"g2::g2_set_dash", _wrap_g2_set_dash},
{"g2::g2_set_font_size", _wrap_g2_set_font_size},
{"g2::g2_set_line_width", _wrap_g2_set_line_width},
{"g2::g2_clear_palette", _wrap_g2_clear_palette},
{"g2::g2_reset_palette", _wrap_g2_reset_palette},
{"g2::g2_allocate_basic_colors", _wrap_g2_allocate_basic_colors},
{"g2::g2_clear", _wrap_g2_clear},
{"g2::g2_set_background", _wrap_g2_set_background},
{"g2::g2_move", _wrap_g2_move},
{"g2::g2_move_r", _wrap_g2_move_r},
{"g2::g2_plot", _wrap_g2_plot},
{"g2::g2_plot_r", _wrap_g2_plot_r},
{"g2::g2_line", _wrap_g2_line},
{"g2::g2_line_r", _wrap_g2_line_r},
{"g2::g2_line_to", _wrap_g2_line_to},
{"g2::g2_poly_line", _wrap_g2_poly_line},
{"g2::g2_triangle", _wrap_g2_triangle},
{"g2::g2_filled_triangle", _wrap_g2_filled_triangle},
{"g2::g2_rectangle", _wrap_g2_rectangle},
{"g2::g2_filled_rectangle", _wrap_g2_filled_rectangle},
{"g2::g2_polygon", _wrap_g2_polygon},
{"g2::g2_filled_polygon", _wrap_g2_filled_polygon},
{"g2::g2_circle", _wrap_g2_circle},
{"g2::g2_filled_circle", _wrap_g2_filled_circle},
{"g2::g2_ellipse", _wrap_g2_ellipse},
{"g2::g2_filled_ellipse", _wrap_g2_filled_ellipse},
{"g2::g2_arc", _wrap_g2_arc},
{"g2::g2_filled_arc", _wrap_g2_filled_arc},
{"g2::g2_string", _wrap_g2_string},
{"g2::g2_image", _wrap_g2_image},
{"g2::g2_set_QP", _wrap_g2_set_QP},
{"g2::g2_plot_QP", _wrap_g2_plot_QP},
{"g2::g2_query_pointer", _wrap_g2_query_pointer},
{"g2::g2_spline", _wrap_g2_spline},
{"g2::g2_b_spline", _wrap_g2_b_spline},
{"g2::g2_raspln", _wrap_g2_raspln},
{"g2::g2_para_3", _wrap_g2_para_3},
{"g2::g2_para_5", _wrap_g2_para_5},
{"g2::g2_filled_spline", _wrap_g2_filled_spline},
{"g2::g2_filled_b_spline", _wrap_g2_filled_b_spline},
{"g2::g2_filled_raspln", _wrap_g2_filled_raspln},
{"g2::g2_filled_para_3", _wrap_g2_filled_para_3},
{"g2::g2_filled_para_5", _wrap_g2_filled_para_5},
{"g2::g2_device_exist", _wrap_g2_device_exist},
{0,0}
};

#ifdef __cplusplus
extern "C"
#endif

XS(SWIG_init) {
    dXSARGS;
    int i;
    for (i = 0; swig_types_initial[i]; i++) {
        swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
    }
    
    /* Install commands */
    for (i = 0; swig_commands[i].name; i++) {
        newXS((char*) swig_commands[i].name,swig_commands[i].wrapper, (char*)__FILE__);
    }
    
    /* Install variables */
    for (i = 0; swig_variables[i].name; i++) {
        SV *sv;
        sv = perl_get_sv((char*) swig_variables[i].name, TRUE | 0x2);
        if (swig_variables[i].type) {
            SWIG_MakePtr(sv,(void *)1, *swig_variables[i].type,0);
        }else {
            sv_setiv(sv,(IV) 0);
        }
        swig_create_magic(sv, (char *) swig_variables[i].name, swig_variables[i].set, swig_variables[i].get); 
    }
    
    /* Install constant */
    for (i = 0; swig_constants[i].type; i++) {
        SV *sv;
        sv = perl_get_sv((char*)swig_constants[i].name, TRUE | 0x2);
        switch(swig_constants[i].type) {
            case SWIG_INT:
            sv_setiv(sv, (IV) swig_constants[i].lvalue);
            break;
            case SWIG_FLOAT:
            sv_setnv(sv, (double) swig_constants[i].dvalue);
            break;
            case SWIG_STRING:
            sv_setpv(sv, (char *) swig_constants[i].pvalue);
            break;
            case SWIG_POINTER:
            SWIG_MakePtr(sv, swig_constants[i].pvalue, *(swig_constants[i].ptype),0);
            break;
            case SWIG_BINARY:
            /*      obj = SWIG_NewPackedObj(swig_constants[i].pvalue, swig_constants[i].lvalue, *(swig_constants[i].ptype)); */
            break;
            default:
            break;
        }
        SvREADONLY_on(sv);
    }
    
    ST(0) = &PL_sv_yes;
    XSRETURN(1);
}

