[REFERENCES]

.I The energy parameters are taken from:

D.H. Mathews, J. Sabina, M. Zuker and H. Turner (1999),
"Expanded Sequence Dependence of Thermodynamic Parameters Provides Robust Prediction of RNA Secondary Structure",
JMB: 288, pp 911-940

A Walter, D Turner, J Kim, M Lyttle, P Mueller, D Mathews, M Zuker (1994),
"Coaxial stacking of helices enhances binding of oligoribonucleotides.",
PNAS: 91, pp 9218-9222

