[AUTHOR]

Ivo L Hofacker, Stephan Bernhart, Ronny Lorenz

[>REFERENCES]

The algorithm is a variant of the dynamic programming algorithms of M. Zuker and P. Stiegler (mfe)
and J.S. McCaskill (pf) adapted for sets of aligned sequences with covariance information.

Ivo L. Hofacker, Martin Fekete, and Peter F. Stadler (2002),
"Secondary Structure Prediction for Aligned RNA Sequences",
J.Mol.Biol.: 319, pp 1059-1066.

Stephan H. Bernhart, Ivo L. Hofacker, Sebastian Will, Andreas R. Gruber, and Peter F. Stadler (2008),
"RNAalifold: Improved consensus structure prediction for RNA alignments",
BMC Bioinformatics: 9, pp 474

[SEE ALSO]

The ALIDOT package http://www.tbi.univie.ac.at/RNA/ALIDOT/
