[AUTHOR]

Ivo L Hofacker

[EXAMPLES]

To search 5 times for sequences forming a simple hairpin structure interrupted by one GA mismatch call

.nf
.ft CW
  $ RNAinverse -R 5
.ft
.fi


and enter the lines

.nf
.ft CW
  (((.(((....))).)))
  NNNgNNNNNNNNNNaNNN
.ft
.fi


[>REFERENCES]

D.H. Turner, N. Sugimoto, S.M. Freier (1988),
"RNA structure prediction",
Ann Rev Biophys Biophys Chem: 17, pp 167-192

M. Zuker, P. Stiegler (1981),
"Optimal computer folding of large RNA sequences using thermodynamic and auxiliary information",
Nucl Acid Res: 9, pp 133-148

J.S. McCaskill (1990),
"The equilibrium partition function and base pair binding probabilities for RNA secondary structures",
Biopolymers: 29, pp 1105-1119
