/their secondary structures./
To do this the partition function and matrix of base pairing probabilities is
computed for each sequence. The probability matrix is then condensed into a
vector holding for each base the probabilities of being unpaired, paired
upstream, or paired downstream, respectively. These profiles are compared
by a standard alignment algorithm.

The base pair probabilities are also saved as postscript "dot plots" (as in
RNAfold) in the files  "name_dp.ps", where name is the name of the sequence,
or a number if unnamed.

[AUTHOR]

Peter F Stadler, Ivo L Hofacker, Sebastian Bonhoeffer.

[>REFERENCES]

S. Bonhoeffer, J.S. McCaskill, P.F. Stadler, P. Schuster (1993),
"RNA multi-structure landscapes",
Euro Biophys J:22, pp 13-24
