[AUTHOR]

Hakim Tafer, Ivo L. Hofacker

[>REFERENCES]

The calculation of duplex structure is based on dynamic programming algorithm originally
developed by Rehmsmeier and in parallel by Hofacker.

H. Tafer and I.L. Hofacker (2008),
"RNAplex: a fast tool for RNA-RNA interaction search.",
Bioinformatics: 24(22), pp 2657-2663

S. Bonhoeffer, J.S. McCaskill, P.F. Stadler, P. Schuster (1993),
"RNA multi-structure landscapes",
Euro Biophys J: 22, pp 13-24
