[AUTHOR]

Ivo L Hofacker, Stefan Wuchty, Walter Fontana, Ronny Lorenz

[>REFERENCES]

S. Wuchty, W. Fontana, I. L. Hofacker and P. Schuster (1999),
"Complete Suboptimal Folding of RNA and the Stability of Secondary Structures",
Biopolymers: 49, pp 145-165

M. Zuker (1989),
"On Finding All Suboptimal Foldings of an RNA Molecule",
Science 244.4900, pp 48-52

Y. Ding, and C.E. Lawrence (2003),
"A statistical sampling algorithm for RNA secondary structure prediction",
Nucleic Acids Research 31.24, pp 7280-7301
